server:
  port: 8770
spring:
  profiles:
    active: git
  application:
    name: whale-cloud-config
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://gitee.com/mearnic/whale-cloud-config.git
          username: 1335666107@qq.com
          password: '{cipher}AEB0gm5W7kykBv3cmTSkmSayeKxfrhckxb6L07EBcjlw1byoEGD6YfSwa838h8YwfhpKXbpKR4fh4ZPyOe7QzjWsQwBcDRJaiLokHNOZtSawSXzutXiTBJ3/QCHlWHRDqKs='
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: root
    password: tiger
  security:
    user:
      name: root
      password: tiger


management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer:tiger@host.docker.internal:8760/eureka/,http://peer:tiger@host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true