server:
  port: 8770
spring:
  profiles:
    include: test-base, test-encrypt
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: ${cloud.config.uri}
          username: ${cloud.config.username}
          password: ${cloud.config.password}
  rabbitmq:
    host: ${db.rabbitmq.host}
    port: ${db.rabbitmq.port}
    password: ${db.rabbitmq.password}
    username: ${db.rabbitmq.username}
  security:
    user:
      name: ${default.account.security.username}
      password: ${default.account.security.password}

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer:tiger@host.docker.internal:8760/eureka/,http://peer:tiger@host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
