server:
  port: 8770
spring:
  profiles:
#    active: git
    include: ${spring.profiles.active:dev}, ${spring.profiles.active:dev-encrypt}
  application:
    name: whale-cloud-config
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: ${cloud.config.uri}
          username: ${cloud.config.username}
          password: ${cloud.config.password}
  rabbitmq:
    host: ${db.rabbitmq.host}
    port: ${db.rabbitmq.port}
    name: ${db.rabbitmq.username}
    password: ${db.rabbitmq.password}
  security:
    user:
      name: ${default.account.security.username}
      password: ${default.account.security.password}

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${cloud.eureka.url}
  instance:
    prefer-ip-address: true