version: '2'
services:
  whale-cloud-eureka-1:
    build: .
    image: whale-cloud-eureka
    environment:
      - server.port=8760
      - JAVA_OPTS='-Xmx64m -Xms64m'
    ports:
      - "8760:8760"
    volumes:
      - /usr/local/var/logs/whale-docker/eureka1:/usr/local/var/logs/whale/eureka
    container_name: whale-cloud-eureka1
  whale-cloud-eureka-2:
    image: whale-cloud-eureka
    environment:
      - server.port=8760
      - JAVA_OPTS='-Xmx64m -Xms64m'
    ports:
      - "8761:8760"
    volumes:
      - /usr/local/var/logs/whale-docker/eureka2:/usr/local/var/logs/whale/eureka
    container_name: whale-cloud-eureka2