version: '2.4'
services:
  whale-cloud-eureka-1:
    build: .
    image: whale-cloud-eureka
    environment:
      - eureka.client.service-url.defaultZone=http://peer:tiger@host.docker.internal:8760/eureka/,http://peer:tiger@host.docker.internal:8761/eureka/
      - spring.rabbitmq.host=rabbit
      - JAVA_OPTS='-Xmx64m -Xms64m'
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9999 -jar /usr/local/whale-cloud-eureka-1.0-SNAPSHOT.jar
    ports:
      - "8760:8760"
      - "9760:9999"
    volumes:
      - /usr/local/var/logs/whale-docker/cloud-eureka-1:/usr/local/var/logs/whale/cloud-eureka
    container_name: whale-cloud-eureka-1
  whale-cloud-eureka-2:
    image: whale-cloud-eureka
    environment:
      - eureka.client.service-url.defaultZone=http://peer:tiger@host.docker.internal:8760/eureka/,http://peer:tiger@host.docker.internal:8761/eureka/
      - spring.rabbitmq.host=rabbit
      - JAVA_OPTS='-Xmx64m -Xms64m'
    command: java -jar /usr/local/whale-cloud-eureka-1.0-SNAPSHOT.jar
    ports:
      - "8761:8760"
    volumes:
      - /usr/local/var/logs/whale-docker/cloud-eureka-2:/usr/local/var/logs/whale/cloud-eureka
    container_name: whale-cloud-eureka-2