version: '2'
services:
  whale-cloud-eureka:
    build: .
    environment:
      - server.port=8760
      - JAVA_OPTS='-Xmx64m -Xms64m'
    ports:
      - "8760:8760"
    volumes:
      - /usr/local/var/logs/whale-docker/eureka:/usr/local/var/logs/whale/eureka
    container_name: whale-cloud-eureka
