version: '2'
services:
  open-blog:
    build: .
    environment:
      - JAVA_OPTS='-Xmx256m -Xms256m'
      - eureka.client.service-url.defaultZone=http://whale-cloud-eureka:8760/eureka/
    ports:
      - "3154:3154"
      - "4154:4154"
    links:
      - whale-cloud-eureka
    volumes:
      - /usr/local/var/logs/whale-docker/open-blog:/usr/local/var/logs/whale/open-blog
    container_name: open-blog
