version: '2'
services:
  open-blog:
    build: .
    environment:
      - server.port=3154
      - JAVA_OPTS='-Xmx64m -Xms64m'
    ports:
      - "3154:3154"
    volumes:
      - ~/system/docker/whale/logs/open-blog:/var/logs
    container_name: open-blog
