server:
  port: 8760

spring:
  application:
    name: whale-cloud-eureka
  security:
    user:
      name: peer
      password: tiger

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer:tiger@127.0.0.1:8760/eureka/
#      defaultZone: http://peer:tiger@peer8761:8761/eureka/,http://peer:tiger@peer8762:8762/eureka/,http://peer:tiger@peer8763:8763/eureka/

---
# 启动参数 --spring.profiles.active=peer8761
spring:
  application:
    name: tools-cloud-eureka-8761
  profiles: peer8761
  security:
    user:
      name: peer
      password: 8761

server:
  port: 8761

eureka:
  instance:
    hostname: peer8761
---
# 启动参数 --spring.profiles.active=peer8762
spring:
  application:
    name: tools-cloud-eureka-8762
  profiles: peer8762
  security:
    user:
      name: peer
      password: 8762

server:
  port: 8762

eureka:
  instance:
    hostname: peer8762

---
# 启动参数 --spring.profiles.active=peer8763
spring:
  application:
    name: tools-cloud-eureka-8763
  profiles: peer8763
  security:
    user:
      name: peer
      password: 8763

server:
  port: 8763

eureka:
  instance:
    hostname: peer8763
